### ISSUE TITLE
Null pointer when adding rooms

### ISSUE THREAD

**Issue by youaremysky99** [AY1920S2-CS2103T-W13-2/main#178]
Null pointer exception when adding rooms.

<img width="898" alt="Screenshot 2020-04-04 at 5 25 34 PM" src="https://user-images.githubusercontent.com/34007191/78423505-52d53600-7699-11ea-997e-cc5dbad87bc8.png">
<img width="1109" alt="Screenshot 2020-04-04 at 5 27 01 PM" src="https://user-images.githubusercontent.com/34007191/78423531-7bf5c680-7699-11ea-8d1f-d83a5b5f3ea4.png">

**Comment by hmtey** [comment]
Related? #139 #146 #161

**Comment by hmtey** [comment]
Unable to recreate, might have been solved with the ui updates?
