### ISSUE TITLE
Deleting commands

### ISSUE THREAD

**Issue by youaremysky99** [AY1920S2-CS2103T-W13-2/main#193]
Aside from adding commands, we also need a bunch of deleting commands. If I miss anything, feel free to comment below.

- [x] Delete person command.

- [x] Delete room command.

- [x] Delete reservation

- [x] Delete available services

- [x] Delete booking.

**Comment by hmtey** [comment]
- [ ] delete charged service
- [x] delete bill

**Comment by hmtey** [comment]
Also related to #161

**Comment by dawidjaja** [comment]
Does delete reservation and booking is the same thing?
