### ISSUE TITLE
Rooms can be added without specifying room number

### ISSUE THREAD

**Issue by hmtey** [AY1920S2-CS2103T-W13-2/main#198]
![Screenshot 2020-04-07 14 17 00](https://user-images.githubusercontent.com/44989374/78636284-9f5b8400-78da-11ea-9dfd-99b9e004ce50.png)

**Comment by dawidjaja** [comment]
Could you reupload the image?

**Comment by hmtey** [comment]
input was `addroom rn/`
![Screenshot 2020-04-07 14 17 00](https://user-images.githubusercontent.com/44989374/78658495-cb87fc80-78fc-11ea-925e-ab3ad84ee459.png)

**Comment by dawidjaja** [comment]
Solved
